package codegen

func GeneratedModuleBindings() string {
	return `// Auto-generated by dagger-zig codegen. DO NOT EDIT.
// Regenerate with: dagger develop
//
// In v0.1, this file is a Zig 0.16-safe re-export of the dagger_sdk package.
// In v0.1.1+, it will contain types specific to your module's dependencies.

const sdk = @import("dagger_sdk");

pub const errors = sdk.errors;
pub const querybuilder = sdk.querybuilder;
pub const core = sdk.core;
pub const module = sdk.module;
pub const tracing = sdk.tracing;
pub const spiffe = sdk.spiffe;
pub const spiffe_integration = sdk.spiffe_integration;

pub const Config = sdk.Config;
pub const Logger = sdk.Logger;
pub const StdLogger = sdk.StdLogger;
pub const api = sdk.api;
pub const module_api = sdk.module_api;

pub const Query = sdk.Query;
pub const Container = sdk.Container;
pub const Directory = sdk.Directory;
pub const File = sdk.File;
pub const Secret = sdk.Secret;
pub const CacheVolume = sdk.CacheVolume;
pub const Service = sdk.Service;
pub const GitRepository = sdk.GitRepository;
pub const GitRef = sdk.GitRef;
pub const Host = sdk.Host;
pub const Socket = sdk.Socket;

pub const ContainerID = sdk.ContainerID;
pub const DirectoryID = sdk.DirectoryID;
pub const FileID = sdk.FileID;
pub const SecretID = sdk.SecretID;
pub const CacheVolumeID = sdk.CacheVolumeID;
pub const ServiceID = sdk.ServiceID;
pub const GitRepositoryID = sdk.GitRepositoryID;
pub const GitRefID = sdk.GitRefID;
pub const HostID = sdk.HostID;
pub const SocketID = sdk.SocketID;

pub const Client = sdk.Client;
pub const connect = sdk.connect;
`
}

// UserModuleBuildZig returns the build.zig that Codegen writes into the
// user's source tree. It wires dagger_sdk as a path dependency and
// installs a `module` executable via the `module-runtime` step — the
// contract ModuleRuntime expects (entrypoint /out/bin/module).
//
// The user's module entry point is main.zig at the source root. If they
// need a different file, they can rename it or add a build.zig override
// in a future version.
func UserModuleBuildZig() string {
	return `// Auto-generated by dagger-zig codegen. DO NOT EDIT.
// Regenerate with: dagger develop
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const dagger_sdk = b.dependency("dagger_sdk", .{
        .target = target,
        .optimize = optimize,
    });

    const mod = b.createModule(.{
        .root_source_file = b.path("main.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
        .imports = &.{
            .{ .name = "dagger_sdk", .module = dagger_sdk.module("dagger_sdk") },
        },
    });

    const exe = b.addExecutable(.{
        .name = "module",
        .root_module = mod,
    });
    const install = b.addInstallArtifact(exe, .{});
    const step = b.step("module-runtime", "Install the Dagger module runtime");
    step.dependOn(&install.step);
    b.getInstallStep().dependOn(&install.step);
}
`
}

// UserModuleBuildZigZon returns the build.zig.zon that Codegen writes into
// the user's source tree. It declares dagger_sdk as a path dependency
// pointing at .dagger-sdk-lib — a symlink that ModuleBuildScript creates
// at runtime, linking to the mounted SDK library (/sdk-lib).
func UserModuleBuildZigZon() string {
	return `// Auto-generated by dagger-zig codegen. DO NOT EDIT.
// Regenerate with: dagger develop
.{
    .fingerprint = 0xfc7412522de88121,
    .name = .dagger_user_module,
    .version = "0.1.0",
    .minimum_zig_version = "0.16.0",
    .dependencies = .{
        .dagger_sdk = .{
            .path = ".dagger-sdk-lib",
        },
    },
    .paths = .{
        "build.zig",
        "build.zig.zon",
        "main.zig",
        "internal",
    },
}
`
}