// Auto-generated by dagger-zig codegen. DO NOT EDIT.
// Regenerate with: dagger develop
//
// In v0.1, this file is a Zig 0.16-safe re-export of the dagger_sdk package.
// In v0.1.1+, it will contain types specific to your module's dependencies.

const sdk = @import("dagger_sdk");

pub const errors = sdk.errors;
pub const querybuilder = sdk.querybuilder;
pub const core = sdk.core;
pub const module = sdk.module;
pub const tracing = sdk.tracing;
pub const spiffe = sdk.spiffe;
pub const spiffe_integration = sdk.spiffe_integration;

pub const Config = sdk.Config;
pub const Logger = sdk.Logger;
pub const StdLogger = sdk.StdLogger;
pub const api = sdk.api;
pub const module_api = sdk.module_api;

pub const Query = sdk.Query;
pub const Container = sdk.Container;
pub const Directory = sdk.Directory;
pub const File = sdk.File;
pub const Secret = sdk.Secret;
pub const CacheVolume = sdk.CacheVolume;
pub const Service = sdk.Service;
pub const GitRepository = sdk.GitRepository;
pub const GitRef = sdk.GitRef;
pub const Host = sdk.Host;
pub const Socket = sdk.Socket;

pub const ContainerID = sdk.ContainerID;
pub const DirectoryID = sdk.DirectoryID;
pub const FileID = sdk.FileID;
pub const SecretID = sdk.SecretID;
pub const CacheVolumeID = sdk.CacheVolumeID;
pub const ServiceID = sdk.ServiceID;
pub const GitRepositoryID = sdk.GitRepositoryID;
pub const GitRefID = sdk.GitRefID;
pub const HostID = sdk.HostID;
pub const SocketID = sdk.SocketID;

pub const Client = sdk.Client;
pub const connect = sdk.connect;
